# Generated by Django 3.2.3 on 2021-05-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True, verbose_name='书名')),
                ('pub', models.CharField(default='', max_length=50, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='价格')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='出版社价格')),
            ],
        ),
    ]
